swagger: "2.0"
info:
  version: "0.0.1"
  title: Residence API
# during dev, should point to your local machine
host: localhost:10020
# basePath prefixes all resource paths
basePath: /apiService
#
schemes:
  - http
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
securityDefinitions:
  api_key:
    type: apiKey
    in: header
    name: api_key
paths:

  /getPreferenceValues:
    x-swagger-router-controller: preferenceController
    get:
      # security:
      #   - api_key: [ ]
      operationId: getPreferenceValues
      parameters:
        - name: project_id
          type: string
          in: query
          required: false
      description: Get onboarding related details
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/DVSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/DVFailureResponse"
    

  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  DVSuccessResponse:
    description: HTTP 200 success response. This is used for all success responses.
    properties:
      message:
        type: string
  DVFailureResponse:
    description: Generic failure response.
